version: "3.9"

x-env: &app-env
  POSTGRES_HOSTNAME: "${POSTGRES_HOSTNAME}"
  POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  KEY: "${KEY}"
  SECRET_KEY: "${SECRET_KEY}"
  TELEGRAM_MODERS_CHAT_ID: "${TELEGRAM_MODERS_CHAT_ID}"
  TELEGRAM_SCHOOL_CHATS: "${TELEGRAM_SCHOOL_CHATS}"

services:
  admin-bot:
    image: registry.gitlab.com/f4648/backend/admin-bot:${CI_COMMIT_SHA}
    container_name: 'admin-bot'
    networks:
      - ab
    environment:
      <<: *app-env
    restart: on-failure
    depends_on:
      ab_postgres:
        condition: service_healthy

  ab_postgres:
    image: registry.gitlab.com/f4648/backend/admin-bot:DB-${CI_COMMIT_SHA}
    container_name: 'ab_postgres'
    environment:
      <<: *app-env
    ports:
        - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d admin_bot']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
       - ab
    volumes:
       - ab-db:/db


volumes:
  ab-db:
    name: ab-db
    driver_opts:
      type: local
      device: /srv/db
      o: bind

networks:
  ab:
    name: "ab"

